export const data = {
    
        'team1' : {
            'name' : 'Islamabad United',
            'avatar' : 'https://banner2.cleanpng.com/20180423/gge/kisspng-islamabad-united-karachi-kings-2018-pakistan-super-chinese-nye-5addb3b97a7530.0808854815244789055016.jpg',
            'id' : '1',
            'matches' : 1,
            'won' : 1,
            'lost' : 0,
            'no_result' : 0,
            'win_ratio' : 1.0
        },
            
        'team2' : {
            'name' : 'Karachi Kings',
            'avatar' : 'https://banner2.cleanpng.com/20180601/pq/kisspng-karachi-kings-islamabad-united-2018-pakistan-super-5b10ec05a2f412.5080078515278356536675.jpg',
            'id' : '2',
            'matches' : 5,
            'won' : 2,
            'lost' : 3,
            'no_result' : 0,
            'win_ratio' : 0.4
        },
        'team1_s' : 'IU',
        'team2_s' : 'KK',
        'toss' : 'KK',
        'batting_1': '',
        'venue' : 'Comsats Cricket ground Islamabad',
        'team1_players' : [
            {
                "name" : "Nausherwan Tahir",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'Sheheryar Arshad',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'Salman Anwar',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
                
            },
            {
                "name": 'Noman Ajaz',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'Raja Maooz',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name" : "Ali Raza",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name" : "Zahoor Alam",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name" : "Burhan Khan",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name" : "Haseeb Ansari",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'Naeem Khan',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'ShahJehan Khan',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
        ],
        'team2_players' : [
            {
                "name" : "Hassan Ali",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'Kamran Shahid',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name" : "Ali Waqar",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'Khurum Manzoor',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name" : "Shaoib Ahmed",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'Salman Anwar',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name" : "Burhan Khan",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'Noman Ajaz',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name" : "Haseeb Ansari",
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'Naeem Khan',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
            {
                "name": 'ShahJehan Khan',
                "score" : 0,
                "balls" : 0,
                "fours" : 0,
                "sixes" : 0,
                "thirties": 0,
                "fifties" : 0,
                "centuries" : 0,
                "highest" : 0,
                "b_score" : 0,
                "b_balls" : 0,
                "b_overs" : 0,
                "b_wickets": 0
            }
            ,
        ],
    }